(SIMP-9239) Add GHA workflows to rubygem-simp-cli
simp/rubygem-simp-cli pull request #158
Opened 2021-02-05 02:16 UTC by op-ct

This patch adds standardized GitHub Actions to provide GitHub-based
CI/CD workflows.  Among this first batch are:

* PR GLCI - Auto-trigger corresponding GLCI (if actor has write perms)
* Manual: PR GLCI - Team members can trigger corresponding GLCI for a PR
* PR GLCI Cleanup - Clean up any auto-triggered GLCI pipelines/branches

This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.

CI: SKIP MATRIX
[SIMP-9376] #close
[SIMP-9239] #comment Standardized GHA + assets in rubygem-simp-cli

2021-02-05 02:36 UTC, op-ct commented
This includes a workflow to deploy to rubygems.org.  We used to do this with simp-cli early on, but stopped—is there any value in resuming it now?

2021-02-05 14:42 UTC, lnemsick-simp commented
I do not think it should be deployed as a RubyGem.  Its RPM spec file has dependencies that are essential and render the code useless of absent.

2021-02-05 14:43 UTC, lnemsick-simp commented on .github/workflows/tag_deploy_rubygem.yml
> +  deploy-rubygem:
IMHO this should be omitted.

2021-02-05 14:47 UTC, lnemsick-simp requested changes

2021-02-05 14:47 UTC, lnemsick-simp commented on .travis.yml
> -    ###      - bundle exec rake pkg:gem
The pkg:gem check  is not in the .gitlab-ci.yml.  It needs to be.

2021-02-05 16:26 UTC, lnemsick-simp commented on .gitlab-ci.yml
>        - $SIMP_FULL_MATRIX == "yes"
does this make sense or was this a bad merge?

2021-02-08 14:11 UTC, lnemsick-simp approved these changes

2021-02-08 14:12 UTC, merged