(SIMP-7465) Update to handle chronyd default
simp/rubygem-simp-cli pull request #160
Opened 2021-02-09 21:42 UTC by jeannegreulich

- Add item in network task list to create a hiera link from
  chronyd::servers to simp_options::ntp::servers.
- Update `simp config` to check for chrony settings
  when determining the currently set os value.

SIMP-7465 #close
SIMP-8966 #close

2021-02-09 22:05 UTC, op-ct requested changes

2021-02-09 22:05 UTC, op-ct commented on spec/lib/simp/cli/commands/files/simp_conf_setting_values_poss_scenario.yaml
> +chronyd::servers: "%{hiera('simp_options::ntp::servers')}"
```suggestion
chronyd::servers: "%{alias('simp_options::ntp::servers')}"
```

2021-02-09 22:05 UTC, op-ct commented on spec/lib/simp/cli/commands/files/simp_conf_setting_values_simp_lite_scenario.yaml
> +chronyd::servers: "%{hiera('simp_options::ntp::servers')}"
```suggestion
chronyd::servers: "%{alias('simp_options::ntp::servers')}"
```

2021-02-09 22:05 UTC, op-ct commented on spec/lib/simp/cli/commands/files/simp_conf_with_overrides.yaml
> +chronyd::servers: "%{hiera('simp_options::ntp::servers')}"
```suggestion
chronyd::servers: "%{alias('simp_options::ntp::servers')}"
```

2021-02-09 22:05 UTC, op-ct commented on spec/lib/simp/cli/commands/files/prev_simp_conf.yaml
> +chronyd::servers: "%{hiera('simp_options::ntp::servers')}"
```suggestion
chronyd::servers: "%{alias('simp_options::ntp::servers')}"
```

2021-02-09 22:05 UTC, op-ct commented on spec/lib/simp/cli/config/items/data/simp_options_ntp_servers_spec.rb
> +    it 'returns the ntp servers when no services are running and not chrony file exists' do
```suggestion
    it 'returns the ntp servers when no services are running and no chrony file exists' do
```

2021-02-10 14:46 UTC, lnemsick-simp commented
simp_options_ntp_servers.rb needs to change is `@key` from `simp_options::ntpd::servers` to `simp_options::ntp::servers`.

2021-02-10 14:48 UTC, lnemsick-simp commented
I'll fix the `simp_options::ntdp::servers` references throughout the code and tests and update the changelog entry accordingly

2021-02-10 15:02 UTC, lnemsick-simp commented on lib/simp/cli/config/items/data/chronyd_link_to_ntpservers.rb
> +  class Item::ChronydNTPServersDefault < Item
Class should be named for hieradata setting and name of the file should match the class name.  I'll fix.

2021-02-10 15:05 UTC, lnemsick-simp commented on lib/simp/cli/config/items/data/chronyd_link_to_ntpservers.rb
> +      @key          = 'chronyd::servers'
hieradata key should be chrony::servers.  I'll fix

2021-02-10 16:33 UTC, lnemsick-simp approved these changes

2021-02-10 18:01 UTC, lnemsick-simp commented
Acceptance test failures are due to GitLab runner configuration, not the code changes.

2021-02-10 18:03 UTC, merged